// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace QAAssignment.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("FieldValidationBetField")]
    public partial class FieldValidationBetFieldFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "FieldValidationBetField", "A short summary of the feature", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "FieldValidationBetField .feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate the bet field")]
        [NUnit.Framework.TestCaseAttribute("a", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("b", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("c", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("d", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("e", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("f", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("g", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("h", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("i", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("j", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("k", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("l", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("m", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("n", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("o", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("p", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("q", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("r", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("s", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("t", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("u", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("v", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("w", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("x", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("y", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("z", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("A", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("B", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("Z", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("abc", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("!", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("%", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("$", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("-10", "be accepted", null)]
        [NUnit.Framework.TestCaseAttribute("--", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("0", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("3.14", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("1e3", "be rejected", null)]
        [NUnit.Framework.TestCaseAttribute("100", "be accepted", null)]
        public async System.Threading.Tasks.Task ValidateTheBetField(string input, string result, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("input", input);
            argumentsOfScenario.Add("result", result);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate the bet field", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync("Navigate to the slot game page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.WhenAsync(string.Format("Enter {0} in the bet field", input), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
 await testRunner.ThenAsync(string.Format("The bet field should {0}", result), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
